/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bundled Quantize IR persisted-document contract (StrategyDocument | ComponentDefinition).
 */
export type QuantizeIR = StrategyDocument | ComponentDefinition;
export type JsonValue =
  | boolean
  | number
  | string
  | JsonValue[]
  | {
      [k: string]: JsonValue;
    }
  | null;

export interface StrategyDocument {
  component_refs: ComponentRef[];
  edges: Edge[];
  execution_policy: ExecutionPolicy;
  extensions?: {
    [k: string]: JsonValue;
  } | null;
  nodes: (RegisteredNode | ComponentRefNode)[];
  schedule: ScheduleDaily | ScheduleWeekly | ScheduleMonthly;
  schema_version: "0.1.0";
  strategy: StrategyMeta;
}
/**
 * A pinned reference from a strategy/definition to a specific component version.
 */
export interface ComponentRef {
  component_id: string;
  id: string;
  version: string;
}
/**
 * A directed connection from one node's output port to another node's input port.
 *
 * Persisted via the canonical serializer as ``{"from": [node, port], "to": [node, port]}``.
 */
export interface Edge {
  /**
   * @minItems 2
   * @maxItems 2
   */
  from: [string, string];
  /**
   * @minItems 2
   * @maxItems 2
   */
  to: [string, string];
}
export interface ExecutionPolicy {
  policy: "close_signal_next_session_open";
  transaction_costs: TransactionCosts;
  valuation: "session_close";
}
export interface TransactionCosts {
  bps: number;
  model: "bps";
}
/**
 * An ordinary node referencing a registered (or unknown future) node type by namespaced id.
 */
export interface RegisteredNode {
  extensions?: {
    [k: string]: JsonValue;
  } | null;
  id: string;
  params: {
    [k: string]: JsonValue;
  };
  type_id: string;
  type_version: string;
  ui?: {
    [k: string]: JsonValue;
  } | null;
}
/**
 * The reserved ``component`` node — references a pinned ``component_refs`` entry by ``ref``.
 */
export interface ComponentRefNode {
  extensions?: {
    [k: string]: JsonValue;
  } | null;
  id: string;
  params: {
    [k: string]: JsonValue;
  };
  ref: string;
  type_id: "component";
  ui?: {
    [k: string]: JsonValue;
  } | null;
}
export interface ScheduleDaily {
  kind: "daily";
}
export interface ScheduleWeekly {
  kind: "weekly";
}
export interface ScheduleMonthly {
  kind: "monthly";
}
export interface StrategyMeta {
  description?: string | null;
  id: string;
  name: string;
  provenance: ProvenanceStrategyForkRef;
  version: number;
}
export interface ProvenanceStrategyForkRef {
  contributors: string[];
  created_at: string;
  creator: string;
  duplicable: boolean;
  forked_from?: StrategyForkRef | null;
  owner: string;
  visibility: "private" | "unlisted_readonly" | "unlisted_duplicable";
}
/**
 * Lineage pointer to a (strategy id, strategy version) — version is a positive integer.
 */
export interface StrategyForkRef {
  id: string;
  version: number;
}
/**
 * A standalone, immutable, versioned reusable component.
 */
export interface ComponentDefinition {
  component_id: string;
  component_refs: ComponentRef[];
  description?: string | null;
  exposed_inputs: ExposedPort[];
  exposed_outputs: ExposedPort[];
  exposed_params: ExposedParam[];
  extensions?: {
    [k: string]: JsonValue;
  } | null;
  implementation: GraphImplementation;
  name: string;
  provenance: ProvenanceComponentForkRef;
  schema_version: "0.1.0";
  version: string;
}
/**
 * A component's externally visible port, mapped to one internal node port.
 */
export interface ExposedPort {
  /**
   * @minItems 2
   * @maxItems 2
   */
  maps_to: [string, string];
  name: string;
  type: ScalarType | AssetSetType | CrossSectionType | TimeSeriesType | PortfolioTargetsType;
}
export interface ScalarType {
  dtype: "Number" | "Integer" | "Boolean";
  kind: "Scalar";
}
export interface AssetSetType {
  kind: "AssetSet";
}
export interface CrossSectionType {
  dtype: "Number" | "Boolean";
  kind: "CrossSection";
}
export interface TimeSeriesType {
  dtype: "Number";
  kind: "TimeSeries";
}
export interface PortfolioTargetsType {
  kind: "PortfolioTargets";
}
/**
 * A component parameter, bound to one internal node parameter.
 */
export interface ExposedParam {
  /**
   * @minItems 2
   * @maxItems 2
   */
  binds_to: [string, string];
  name: string;
  schema: {
    [k: string]: JsonValue;
  };
}
export interface GraphImplementation {
  graph: Graph;
  kind: "graph";
}
/**
 * An internal node/edge graph (a component's body for the v0 'graph' implementation).
 */
export interface Graph {
  edges: Edge[];
  nodes: (RegisteredNode | ComponentRefNode)[];
}
export interface ProvenanceComponentForkRef {
  contributors: string[];
  created_at: string;
  creator: string;
  duplicable: boolean;
  forked_from?: ComponentForkRef | null;
  owner: string;
  visibility: "private" | "unlisted_readonly" | "unlisted_duplicable";
}
/**
 * Lineage pointer to a (component id, component version) — version is SemVer.
 */
export interface ComponentForkRef {
  id: string;
  version: string;
}
