/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JsonValue =
  | boolean
  | number
  | string
  | JsonValue[]
  | {
      [k: string]: JsonValue;
    }
  | null;

/**
 * Bundled Quantize HTTP API request/response envelope contract (M9 boundary).
 */
export interface QuantizeApi {
  ApiError?: ApiError;
  AssetSetType?: AssetSetType;
  BacktestRunRequest?: BacktestRunRequest;
  CalendarDto?: CalendarDto;
  CatalogInputPortDto?: CatalogInputPortDto;
  CatalogOutputPortDto?: CatalogOutputPortDto;
  CompatibilityPairDto?: CompatibilityPairDto;
  ComponentList?: ComponentList;
  ComponentListRow?: ComponentListRow;
  ComponentSaved?: ComponentSaved;
  CrossSectionType?: CrossSectionType;
  DatasetList?: DatasetList;
  DatasetListRow?: DatasetListRow;
  DatasetStored?: DatasetStored;
  DatasetUpload?: DatasetUpload;
  ForwardRunRequest?: ForwardRunRequest;
  JsonValue?: JsonValue;
  MetaResponse?: MetaResponse;
  NodeCatalogResponse?: NodeCatalogResponse;
  NodeTypeDto?: NodeTypeDto;
  ObservationDto?: ObservationDto;
  PersistedDiagnostic?: PersistedDiagnostic;
  PersistedEvaluation?: PersistedEvaluation;
  PersistedFill?: PersistedFill;
  PersistedNote?: PersistedNote;
  PersistedOrder?: PersistedOrder;
  PersistedPlanRow?: PersistedPlanRow;
  PersistedRunRecord?: PersistedRunRecord;
  PersistedStaleMark?: PersistedStaleMark;
  PortTypeEntryDto?: PortTypeEntryDto;
  PortfolioTargetsType?: PortfolioTargetsType;
  RunCreated?: RunCreated;
  RunInputProvenance?: RunInputProvenance;
  RunList?: RunList;
  RunListRow?: RunListRow;
  RunRecordResponse?: RunRecordResponse;
  RuntimeDiagnosticDto?: RuntimeDiagnosticDto;
  ScalarType?: ScalarType;
  SemanticDiagnosticDto?: SemanticDiagnosticDto;
  SessionDto?: SessionDto;
  StrategyList?: StrategyList;
  StrategyListRow?: StrategyListRow;
  StrategySaved?: StrategySaved;
  StructuralDiagnosticDto?: StructuralDiagnosticDto;
  TimeSeriesType?: TimeSeriesType;
  TraceEvent?: TraceEvent;
  TraceResponse?: TraceResponse;
  ValidateResponse?: ValidateResponse;
  VersionList?: VersionList;
}
/**
 * The uniform error envelope. ``code`` is a stable machine identifier; ``message`` is human
 * text. Deliberately has no ``context``/``detail`` field — infrastructure internals never leak.
 */
export interface ApiError {
  code: string;
  message: string;
}
export interface AssetSetType {
  kind: "AssetSet";
}
/**
 * A backtest submission. ``last_session`` is optional (defaults to the dataset's last).
 */
export interface BacktestRunRequest {
  dataset_id: string;
  first_session?: string | null;
  initial_cash: number;
  initial_positions?: {
    [k: string]: number;
  };
  last_session?: string | null;
  strategy_id: string;
  strategy_version: number;
}
export interface CalendarDto {
  exchange: string;
  sessions: SessionDto[];
  timezone: string;
}
/**
 * One trading session: the exchange-local date plus UTC open/close instants.
 */
export interface SessionDto {
  close_at: string;
  open_at: string;
  session_date: string;
}
/**
 * One declared input port of a node type.
 */
export interface CatalogInputPortDto {
  name: string;
  port_type: ScalarType | AssetSetType | CrossSectionType | TimeSeriesType | PortfolioTargetsType;
  required: boolean;
}
export interface ScalarType {
  dtype: "Number" | "Integer" | "Boolean";
  kind: "Scalar";
}
export interface CrossSectionType {
  dtype: "Number" | "Boolean";
  kind: "CrossSection";
}
export interface TimeSeriesType {
  dtype: "Number";
  kind: "TimeSeries";
}
export interface PortfolioTargetsType {
  kind: "PortfolioTargets";
}
/**
 * One declared output port of a node type.
 */
export interface CatalogOutputPortDto {
  name: string;
  port_type: ScalarType | AssetSetType | CrossSectionType | TimeSeriesType | PortfolioTargetsType;
}
/**
 * One allowed ``(source -> destination)`` edge over the port-type lattice.
 */
export interface CompatibilityPairDto {
  destination: ScalarType | AssetSetType | CrossSectionType | TimeSeriesType | PortfolioTargetsType;
  source: ScalarType | AssetSetType | CrossSectionType | TimeSeriesType | PortfolioTargetsType;
}
export interface ComponentList {
  components: ComponentListRow[];
}
/**
 * One component summary row — mirrors ``persistence.documents.ComponentSummary``.
 */
export interface ComponentListRow {
  component_id: string;
  name: string;
  saved_at: string;
  schema_version: string;
  version: string;
}
/**
 * Acknowledgement of a persisted component definition (version is a SemVer string).
 */
export interface ComponentSaved {
  component_id: string;
  version: string;
}
export interface DatasetList {
  datasets: DatasetListRow[];
}
/**
 * One dataset discovery row — mirrors ``persistence.datasets.DatasetSummary``.
 *
 * Stored columns ONLY (identity + both fingerprints + ``saved_at``); deliberately no
 * ``sessions``/``assets`` counts — those need a per-dataset payload decode (use ``DatasetStored``
 * from ``GET /v1/datasets/{id}`` when a dataset is selected).
 */
export interface DatasetListRow {
  calendar_fingerprint: string;
  dataset_fingerprint: string;
  dataset_id: string;
  saved_at: string;
}
/**
 * Metadata for a stored dataset — the content-addressed id plus both provenance fingerprints
 * and simple counts. NEVER carries the payload (fetch-metadata returns this, not the data).
 */
export interface DatasetStored {
  assets: number;
  calendar_fingerprint: string;
  dataset_fingerprint: string;
  dataset_id: string;
  sessions: number;
}
/**
 * A full uploaded dataset: the calendar plus per-asset observation series (asset -> rows).
 */
export interface DatasetUpload {
  calendar: CalendarDto;
  observations: {
    [k: string]: ObservationDto[];
  };
}
/**
 * One session's open/close prices for one asset, with explicit availability instants.
 */
export interface ObservationDto {
  close_available_at: string;
  close_price: number;
  open_available_at: string;
  open_price: number;
  session_date: string;
}
/**
 * A forward-replay submission — identical to backtest but ``last_session`` is REQUIRED.
 */
export interface ForwardRunRequest {
  dataset_id: string;
  first_session?: string | null;
  initial_cash: number;
  initial_positions?: {
    [k: string]: number;
  };
  last_session: string;
  strategy_id: string;
  strategy_version: number;
}
/**
 * Service identity: the API version plus the format versions a client must understand.
 */
export interface MetaResponse {
  api_version: string;
  record_format: number;
  schema_version: string;
  trace_format: number;
}
/**
 * The full node-catalog projection: versions, a content digest, the lattice, the compatible
 * edges, and every registered node type.
 */
export interface NodeCatalogResponse {
  api_version: string;
  catalog_digest: string;
  compatibility: CompatibilityPairDto[];
  node_types: NodeTypeDto[];
  port_types: PortTypeEntryDto[];
  schema_version: string;
}
/**
 * One registered node type: identity, typed ports, and its parameter JSON Schema (if any).
 */
export interface NodeTypeDto {
  description: string;
  display_name: string;
  inputs: CatalogInputPortDto[];
  outputs: CatalogOutputPortDto[];
  parameter_schema: {
    [k: string]: JsonValue;
  } | null;
  type_id: string;
  type_version: string;
}
/**
 * One lattice member paired with its compact human ``label`` (e.g. ``"Scalar[Number]"``).
 */
export interface PortTypeEntryDto {
  label: string;
  port_type: ScalarType | AssetSetType | CrossSectionType | TimeSeriesType | PortfolioTargetsType;
}
export interface PersistedDiagnostic {
  code: string;
  message: string;
  node_path: string[];
  subject: string | null;
}
export interface PersistedEvaluation {
  evaluation_instant: string;
  fill_session: string | null;
  ok: boolean;
  orders: PersistedOrder[];
  plans: PersistedPlanRow[];
  portfolio_value: number | null;
  projected_cash: number | null;
  scheduled_fill_instant: string | null;
  session_date: string;
  target_cash: number | null;
  target_weights: [string, number][];
}
export interface PersistedOrder {
  asset: string;
  quantity: number;
  side: string;
}
/**
 * One reconciliation explanation row (ADR-0005 AssetPlan), verbatim.
 */
export interface PersistedPlanRow {
  action: string;
  asset: string;
  current_quantity: number;
  delta_quantity: number;
  price: number;
  target_notional: number;
  target_quantity: number;
  target_weight: number;
}
export interface PersistedFill {
  actual_fill_instant: string;
  asset: string;
  cash_delta: number;
  cost: number;
  price: number;
  quantity: number;
  scaled: boolean;
  session_date: string;
  side: string;
}
export interface PersistedNote {
  code: string;
  message: string;
  session_date: string;
}
/**
 * The complete durable fact set of one run (trace stored separately, same transaction).
 */
export interface PersistedRunRecord {
  diagnostics: PersistedDiagnostic[];
  evaluations: PersistedEvaluation[];
  exchange: string;
  fills: PersistedFill[];
  final_cash: number;
  final_positions: [string, number][];
  first_session: string | null;
  input_provenance: RunInputProvenance;
  last_session: string | null;
  max_drawdown: number;
  mode: string;
  notes: PersistedNote[];
  ok: boolean;
  record_format: number;
  returns: number[];
  run_id: string;
  stale_marks: PersistedStaleMark[];
  strategy_id: string;
  strategy_version: number;
  timezone: string;
  total_return: number;
  valuations: [string, number][];
}
/**
 * The run's input identity: recorded content hashes, or an explicit honest unknown.
 */
export interface RunInputProvenance {
  calendar_hash?: string | null;
  dataset_hash?: string | null;
  status: "recorded" | "unknown";
}
export interface PersistedStaleMark {
  asset: string;
  mark_date: string;
  session_date: string;
}
/**
 * Acknowledgement of a submitted (and synchronously executed + persisted) run.
 */
export interface RunCreated {
  run_id: string;
}
export interface RunList {
  runs: RunListRow[];
}
/**
 * One run summary row — mirrors ``persistence.runs.RunSummary``.
 */
export interface RunListRow {
  first_session: string | null;
  last_session: string | null;
  mode: string;
  ok: boolean;
  run_id: string;
  saved_at: string;
  strategy_id: string;
  strategy_version: number;
  total_return: number;
}
/**
 * The stored run record plus whether its inputs were fingerprinted (recorded provenance).
 *
 * ``replay_verifiable`` lives BESIDE the record, never inside it: the ``record`` value is the
 * stored artifact verbatim; ``replay_verifiable`` is a derived, non-persisted flag.
 */
export interface RunRecordResponse {
  record: PersistedRunRecord;
  replay_verifiable: boolean;
}
/**
 * One resolution/wiring/terminal fault: located by execution ``node_path``, not ``loc``.
 */
export interface RuntimeDiagnosticDto {
  code: string;
  message: string;
  node_path: string[];
  subject?: string | null;
}
/**
 * One semantic (M2) fault. Same shape as the structural DTO; kept a distinct type.
 */
export interface SemanticDiagnosticDto {
  code: string;
  loc: (string | number)[];
  message: string;
  subject?: string | null;
}
export interface StrategyList {
  strategies: StrategyListRow[];
}
/**
 * One strategy summary row — mirrors ``persistence.documents.StrategySummary``.
 */
export interface StrategyListRow {
  name: string;
  saved_at: string;
  schema_version: string;
  strategy_id: string;
  version: number;
}
/**
 * Acknowledgement of a persisted strategy version.
 */
export interface StrategySaved {
  strategy_id: string;
  version: number;
}
/**
 * One structural (M1.2) fault: located by document ``loc`` (e.g. ``("edges", 2, "from")``).
 */
export interface StructuralDiagnosticDto {
  code: string;
  loc: (string | number)[];
  message: string;
  subject?: string | null;
}
/**
 * One structured decision-trace event (envelope only; ``payload`` shape is per-node).
 */
export interface TraceEvent {
  component_path?: string[];
  event_type: string;
  node_id: string;
  payload: {
    [k: string]: JsonValue;
  };
  run_id: string;
  timestamp: string;
}
/**
 * The run's decision-trace events in stored sequence order (optionally session-filtered).
 */
export interface TraceResponse {
  events: TraceEvent[];
}
/**
 * The run-faithful validation verdict. ``ok`` is true only when every layer is clean; on ok
 * it additionally reports ``warmup_sessions`` (the resolved warm-up the run would require).
 */
export interface ValidateResponse {
  ok: boolean;
  runtime: RuntimeDiagnosticDto[];
  semantic: SemanticDiagnosticDto[];
  structural: StructuralDiagnosticDto[];
  warmup_sessions?: number | null;
}
/**
 * The ascending version numbers stored for one strategy id.
 */
export interface VersionList {
  versions: number[];
}
